site_name: MirrorMate AI Documentation
site_description: Documentation for MirrorMate AI APIs and SDKs
repo_url: https://github.com/rootsec1/mirrormate.ai

nav:
  - Home: index.md

plugins:
  - techdocs-core
